### ISSUE TITLE
yarn test issue

### ISSUE THREAD

**Issue by RaulTsc** [liviuignat/heimdall#26]
Running `yarn test` gives

`Determining test suites to run...2017-01-24 18:57 node[11695] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2
d_register_rpc() => (null) (-22)
2017-01-24 18:57 node[11695] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-01-24 18:57 node[11695] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1282:11`

This was fixed by doing 

`brew link automake`
`brew install --HEAD watchman`

https://github.com/facebook/react-native/issues/910

Other people might have this problem aswell. If we don't plan on fixing it atm we should at least include the fix in the README.

**Comment by liviuignat** [comment]
I don't have this problem, but I installed yarn with `npm install yarn -g` and I think this is not the recommended way anymore.

**Comment by RaulTsc** [comment]
I also installed it globally, I don't think that's the problem though. The reporter in the RN issue is using npm. I think `watchman` might be a dependency of `jest` and it gets screwed up somehow.
